FROM mcr.microsoft.com/playwright:v1.58.2-noble

WORKDIR /app

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

COPY frontend/package.json frontend/pnpm-lock.yaml /app/frontend/

WORKDIR /app/frontend

RUN pnpm install --frozen-lockfile

COPY ./frontend /app/frontend

ARG VITE_API_URL
