// This file is auto-generated by @hey-api/openapi-ts

export const AgentConfigCreateSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        role: {
            type: 'string',
            title: 'Role'
        },
        responsibilities: {
            type: 'string',
            title: 'Responsibilities',
            default: ''
        },
        system_prompt: {
            type: 'string',
            title: 'System Prompt',
            default: ''
        },
        model_config_name: {
            type: 'string',
            title: 'Model Config Name',
            default: ''
        },
        workflow_order: {
            type: 'integer',
            title: 'Workflow Order',
            default: 1
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        skills: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Skills'
        },
        tools: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Tools'
        },
        max_iterations: {
            type: 'integer',
            title: 'Max Iterations',
            default: 5
        }
    },
    type: 'object',
    required: ['name', 'role'],
    title: 'AgentConfigCreate'
} as const;

export const AgentConfigPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        role: {
            type: 'string',
            title: 'Role'
        },
        responsibilities: {
            type: 'string',
            title: 'Responsibilities'
        },
        system_prompt: {
            type: 'string',
            title: 'System Prompt'
        },
        model_config_name: {
            type: 'string',
            title: 'Model Config Name'
        },
        workflow_order: {
            type: 'integer',
            title: 'Workflow Order'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        skills: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Skills'
        },
        tools: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Tools'
        },
        max_iterations: {
            type: 'integer',
            title: 'Max Iterations'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'name', 'role', 'responsibilities', 'system_prompt', 'model_config_name', 'workflow_order', 'is_active', 'skills', 'tools', 'max_iterations', 'created_at'],
    title: 'AgentConfigPublic'
} as const;

export const AgentConfigUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        role: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Role'
        },
        responsibilities: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Responsibilities'
        },
        system_prompt: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'System Prompt'
        },
        model_config_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Model Config Name'
        },
        workflow_order: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Workflow Order'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        },
        skills: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Skills'
        },
        tools: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tools'
        },
        max_iterations: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Max Iterations'
        }
    },
    type: 'object',
    title: 'AgentConfigUpdate'
} as const;

export const AgentConfigsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/AgentConfigPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'AgentConfigsPublic'
} as const;

export const AgentStepSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        agent_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Agent Id'
        },
        agent_name: {
            type: 'string',
            title: 'Agent Name'
        },
        role: {
            type: 'string',
            title: 'Role'
        },
        input: {
            type: 'string',
            title: 'Input',
            default: ''
        },
        output: {
            type: 'string',
            title: 'Output',
            default: ''
        },
        thinking: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Thinking'
        },
        title_candidates: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Title Candidates'
        },
        status: {
            type: 'string',
            title: 'Status',
            default: 'pending'
        },
        started_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Started At'
        },
        ended_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ended At'
        },
        messages: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Messages'
        },
        tools_used: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Tools Used'
        },
        skills_activated: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Skills Activated'
        },
        iteration_count: {
            type: 'integer',
            title: 'Iteration Count',
            default: 0
        }
    },
    type: 'object',
    required: ['agent_name', 'role'],
    title: 'AgentStep'
} as const;

export const AnalysesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ArticleAnalysisPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'AnalysesPublic'
} as const;

export const ApiConfigSchema = {
    properties: {
        items_path: {
            type: 'string',
            title: 'Items Path'
        },
        title_field: {
            type: 'string',
            title: 'Title Field'
        },
        content_field: {
            type: 'string',
            title: 'Content Field'
        },
        url_field: {
            type: 'string',
            title: 'Url Field'
        },
        author_field: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Author Field'
        },
        published_at_field: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Published At Field'
        }
    },
    type: 'object',
    required: ['items_path', 'title_field', 'content_field', 'url_field'],
    title: 'ApiConfig'
} as const;

export const ArticleAnalysisPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        article_id: {
            type: 'string',
            format: 'uuid',
            title: 'Article Id'
        },
        quality_score: {
            type: 'number',
            title: 'Quality Score'
        },
        quality_breakdown: {
            '$ref': '#/components/schemas/QualityBreakdown'
        },
        hook_type: {
            type: 'string',
            title: 'Hook Type'
        },
        framework: {
            type: 'string',
            title: 'Framework'
        },
        emotional_triggers: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Emotional Triggers'
        },
        key_phrases: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Key Phrases'
        },
        keywords: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Keywords'
        },
        structure: {
            '$ref': '#/components/schemas/ArticleStructure'
        },
        style: {
            '$ref': '#/components/schemas/ArticleStyle'
        },
        target_audience: {
            type: 'string',
            title: 'Target Audience'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'article_id', 'quality_score', 'quality_breakdown', 'hook_type', 'framework', 'emotional_triggers', 'key_phrases', 'keywords', 'structure', 'style', 'target_audience', 'created_at'],
    title: 'ArticleAnalysisPublic'
} as const;

export const ArticleDetailSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        source_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Source Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url'
        },
        author: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Author'
        },
        published_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Published At'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        input_type: {
            type: 'string',
            title: 'Input Type'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        quality_score: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Quality Score'
        },
        content: {
            type: 'string',
            title: 'Content'
        },
        analysis: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Analysis'
        }
    },
    type: 'object',
    required: ['id', 'source_id', 'title', 'url', 'author', 'published_at', 'status', 'input_type', 'created_at', 'content'],
    title: 'ArticleDetail'
} as const;

export const ArticlePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        source_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Source Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url'
        },
        author: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Author'
        },
        published_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Published At'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        input_type: {
            type: 'string',
            title: 'Input Type'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        quality_score: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Quality Score'
        }
    },
    type: 'object',
    required: ['id', 'source_id', 'title', 'url', 'author', 'published_at', 'status', 'input_type', 'created_at'],
    title: 'ArticlePublic'
} as const;

export const ArticleStructureSchema = {
    properties: {
        intro: {
            type: 'string',
            title: 'Intro',
            default: ''
        },
        body_sections: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Body Sections'
        },
        cta: {
            type: 'string',
            title: 'Cta',
            default: ''
        }
    },
    type: 'object',
    title: 'ArticleStructure'
} as const;

export const ArticleStyleSchema = {
    properties: {
        tone: {
            type: 'string',
            title: 'Tone',
            default: ''
        },
        formality: {
            type: 'string',
            title: 'Formality',
            default: ''
        },
        avg_sentence_length: {
            type: 'number',
            title: 'Avg Sentence Length',
            default: 0
        }
    },
    type: 'object',
    title: 'ArticleStyle'
} as const;

export const ArticlesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ArticlePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ArticlesPublic'
} as const;

export const BearerResponseSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type'
        }
    },
    type: 'object',
    required: ['access_token', 'token_type'],
    title: 'BearerResponse'
} as const;

export const Body_auth_reset_forgot_passwordSchema = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        }
    },
    type: 'object',
    required: ['email'],
    title: 'Body_auth-reset:forgot_password'
} as const;

export const Body_auth_reset_reset_passwordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        password: {
            type: 'string',
            title: 'Password'
        }
    },
    type: 'object',
    required: ['token', 'password'],
    title: 'Body_auth-reset:reset_password'
} as const;

export const Body_auth_verify_request_tokenSchema = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        }
    },
    type: 'object',
    required: ['email'],
    title: 'Body_auth-verify:request-token'
} as const;

export const Body_auth_verify_verifySchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        }
    },
    type: 'object',
    required: ['token'],
    title: 'Body_auth-verify:verify'
} as const;

export const DraftPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        source_article_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            title: 'Source Article Ids'
        },
        workflow_run_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Workflow Run Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        title_candidates: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Title Candidates'
        },
        content: {
            type: 'string',
            title: 'Content'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        edit_history: {
            items: {
                '$ref': '#/components/schemas/EditHistoryEntry'
            },
            type: 'array',
            title: 'Edit History'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'source_article_ids', 'workflow_run_id', 'title', 'title_candidates', 'content', 'status', 'edit_history', 'created_at'],
    title: 'DraftPublic'
} as const;

export const DraftUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        content: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content'
        },
        status: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Status'
        }
    },
    type: 'object',
    title: 'DraftUpdate'
} as const;

export const DraftsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/DraftPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'DraftsPublic'
} as const;

export const EditHistoryEntrySchema = {
    properties: {
        content: {
            type: 'string',
            title: 'Content'
        },
        edited_at: {
            type: 'string',
            format: 'date-time',
            title: 'Edited At'
        },
        note: {
            type: 'string',
            title: 'Note',
            default: ''
        }
    },
    type: 'object',
    required: ['content'],
    title: 'EditHistoryEntry'
} as const;

export const ErrorModelSchema = {
    properties: {
        detail: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    additionalProperties: {
                        type: 'string'
                    },
                    type: 'object'
                }
            ],
            title: 'Detail'
        }
    },
    type: 'object',
    required: ['detail'],
    title: 'ErrorModel'
} as const;

export const FetchConfigSchema = {
    properties: {
        interval_minutes: {
            type: 'integer',
            title: 'Interval Minutes',
            default: 60
        },
        max_items_per_fetch: {
            type: 'integer',
            title: 'Max Items Per Fetch',
            default: 20
        }
    },
    type: 'object',
    title: 'FetchConfig'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const LLMModelConfigCreateSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        provider_type: {
            type: 'string',
            enum: ['openai_compatible', 'kimi'],
            title: 'Provider Type',
            default: 'kimi'
        },
        base_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Base Url'
        },
        api_key: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Api Key'
        },
        model_id: {
            type: 'string',
            title: 'Model Id'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        }
    },
    type: 'object',
    required: ['name', 'model_id'],
    title: 'LLMModelConfigCreate'
} as const;

export const LLMModelConfigPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        provider_type: {
            type: 'string',
            title: 'Provider Type'
        },
        base_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Base Url'
        },
        api_key_masked: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Api Key Masked'
        },
        model_id: {
            type: 'string',
            title: 'Model Id'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'name', 'provider_type', 'base_url', 'api_key_masked', 'model_id', 'is_active', 'created_at'],
    title: 'LLMModelConfigPublic'
} as const;

export const LLMModelConfigUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        provider_type: {
            anyOf: [
                {
                    type: 'string',
                    enum: ['openai_compatible', 'kimi']
                },
                {
                    type: 'null'
                }
            ],
            title: 'Provider Type'
        },
        base_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Base Url'
        },
        api_key: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Api Key'
        },
        model_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Model Id'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        }
    },
    type: 'object',
    title: 'LLMModelConfigUpdate'
} as const;

export const LLMModelConfigsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/LLMModelConfigPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'LLMModelConfigsPublic'
} as const;

export const LLMProviderPublicSchema = {
    properties: {
        api_key_masked: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Api Key Masked'
        },
        default_model: {
            type: 'string',
            title: 'Default Model'
        }
    },
    type: 'object',
    required: ['default_model'],
    title: 'LLMProviderPublic'
} as const;

export const LLMProvidersPublicSchema = {
    properties: {
        kimi: {
            '$ref': '#/components/schemas/LLMProviderPublic'
        },
        claude: {
            '$ref': '#/components/schemas/LLMProviderPublic'
        },
        openai: {
            '$ref': '#/components/schemas/LLMProviderPublic'
        }
    },
    type: 'object',
    required: ['kimi', 'claude', 'openai'],
    title: 'LLMProvidersPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const ModelDefaultsSchema = {
    properties: {
        default_model_provider: {
            type: 'string',
            title: 'Default Model Provider',
            default: 'kimi'
        },
        default_model_id: {
            type: 'string',
            title: 'Default Model Id',
            default: 'moonshot-v1-32k'
        }
    },
    type: 'object',
    title: 'ModelDefaults'
} as const;

export const OrchestratorConfigSchema = {
    properties: {
        enabled: {
            type: 'boolean',
            title: 'Enabled',
            default: false
        }
    },
    type: 'object',
    title: 'OrchestratorConfig'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const QualityBreakdownSchema = {
    properties: {
        content_depth: {
            type: 'number',
            title: 'Content Depth',
            default: 0
        },
        readability: {
            type: 'number',
            title: 'Readability',
            default: 0
        },
        originality: {
            type: 'number',
            title: 'Originality',
            default: 0
        },
        virality_potential: {
            type: 'number',
            title: 'Virality Potential',
            default: 0
        }
    },
    type: 'object',
    title: 'QualityBreakdown'
} as const;

export const RewriteSectionRequestSchema = {
    properties: {
        selected_text: {
            type: 'string',
            title: 'Selected Text'
        },
        context: {
            type: 'string',
            title: 'Context',
            default: ''
        }
    },
    type: 'object',
    required: ['selected_text'],
    title: 'RewriteSectionRequest'
} as const;

export const RewriteSectionResponseSchema = {
    properties: {
        rewritten_text: {
            type: 'string',
            title: 'Rewritten Text'
        }
    },
    type: 'object',
    required: ['rewritten_text'],
    title: 'RewriteSectionResponse'
} as const;

export const RoutingEventSchema = {
    properties: {
        timestamp: {
            type: 'string',
            format: 'date-time',
            title: 'Timestamp'
        },
        from_agent: {
            type: 'string',
            title: 'From Agent'
        },
        to_agent: {
            type: 'string',
            title: 'To Agent'
        },
        reason: {
            type: 'string',
            title: 'Reason',
            default: ''
        }
    },
    type: 'object',
    required: ['from_agent', 'to_agent'],
    title: 'RoutingEvent'
} as const;

export const SchedulerConfigSchema = {
    properties: {
        default_interval_minutes: {
            type: 'integer',
            title: 'Default Interval Minutes',
            default: 60
        },
        max_concurrent_fetches: {
            type: 'integer',
            title: 'Max Concurrent Fetches',
            default: 3
        }
    },
    type: 'object',
    title: 'SchedulerConfig'
} as const;

export const SearchConfigSchema = {
    properties: {
        tavily_api_key: {
            type: 'string',
            title: 'Tavily Api Key',
            default: ''
        }
    },
    type: 'object',
    title: 'SearchConfig'
} as const;

export const SkillCreateSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            type: 'string',
            title: 'Description',
            default: ''
        },
        body: {
            type: 'string',
            title: 'Body',
            default: ''
        },
        scripts: {
            items: {
                '$ref': '#/components/schemas/SkillScript'
            },
            type: 'array',
            title: 'Scripts'
        },
        needs_network: {
            type: 'boolean',
            title: 'Needs Network',
            default: false
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        source: {
            type: 'string',
            enum: ['imported', 'user'],
            title: 'Source',
            default: 'user'
        },
        imported_from: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Imported From'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'SkillCreate'
} as const;

export const SkillImportBodySchema = {
    properties: {
        content: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content'
        },
        url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url'
        }
    },
    type: 'object',
    title: 'SkillImportBody'
} as const;

export const SkillPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        body: {
            type: 'string',
            title: 'Body'
        },
        scripts: {
            items: {
                '$ref': '#/components/schemas/SkillScript'
            },
            type: 'array',
            title: 'Scripts'
        },
        needs_network: {
            type: 'boolean',
            title: 'Needs Network'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        source: {
            type: 'string',
            title: 'Source'
        },
        imported_from: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Imported From'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'name', 'description', 'body', 'scripts', 'needs_network', 'is_active', 'source', 'imported_from', 'created_at', 'updated_at'],
    title: 'SkillPublic'
} as const;

export const SkillScriptSchema = {
    properties: {
        filename: {
            type: 'string',
            title: 'Filename'
        },
        content: {
            type: 'string',
            title: 'Content'
        },
        language: {
            type: 'string',
            title: 'Language',
            default: 'python'
        }
    },
    type: 'object',
    required: ['filename', 'content'],
    title: 'SkillScript',
    description: 'A script bundled with a skill.'
} as const;

export const SkillUpdateSchema = {
    properties: {
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        body: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Body'
        },
        scripts: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/SkillScript'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Scripts'
        },
        needs_network: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Needs Network'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        }
    },
    type: 'object',
    title: 'SkillUpdate'
} as const;

export const SkillsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/SkillPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'SkillsPublic'
} as const;

export const SourceCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        type: {
            type: 'string',
            title: 'Type'
        },
        url: {
            type: 'string',
            title: 'Url'
        },
        api_key: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Api Key'
        },
        headers: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Headers'
        },
        api_config: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ApiConfig'
                },
                {
                    type: 'null'
                }
            ]
        },
        fetch_config: {
            '$ref': '#/components/schemas/FetchConfig'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        }
    },
    type: 'object',
    required: ['name', 'type', 'url'],
    title: 'SourceCreate'
} as const;

export const SourcePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        type: {
            type: 'string',
            title: 'Type'
        },
        url: {
            type: 'string',
            title: 'Url'
        },
        api_config: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ApiConfig'
                },
                {
                    type: 'null'
                }
            ]
        },
        fetch_config: {
            '$ref': '#/components/schemas/FetchConfig'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        last_fetched_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Fetched At'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'name', 'type', 'url', 'api_config', 'fetch_config', 'is_active', 'last_fetched_at', 'created_at'],
    title: 'SourcePublic'
} as const;

export const SourceUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url'
        },
        api_key: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Api Key'
        },
        headers: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Headers'
        },
        api_config: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ApiConfig'
                },
                {
                    type: 'null'
                }
            ]
        },
        fetch_config: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/FetchConfig'
                },
                {
                    type: 'null'
                }
            ]
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        }
    },
    type: 'object',
    title: 'SourceUpdate'
} as const;

export const SourcesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/SourcePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'SourcesPublic'
} as const;

export const SubmitResponseSchema = {
    properties: {
        article_id: {
            type: 'string',
            title: 'Article Id'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['article_id', 'status', 'message'],
    title: 'SubmitResponse'
} as const;

export const SubmitTextSchema = {
    properties: {
        mode: {
            type: 'string',
            title: 'Mode',
            default: 'text'
        },
        title: {
            type: 'string',
            title: 'Title',
            default: ''
        },
        content: {
            type: 'string',
            title: 'Content',
            default: ''
        },
        url: {
            type: 'string',
            title: 'Url',
            default: ''
        }
    },
    type: 'object',
    title: 'SubmitText'
} as const;

export const SystemConfigPublicSchema = {
    properties: {
        llm_providers: {
            '$ref': '#/components/schemas/LLMProvidersPublic'
        },
        scheduler: {
            '$ref': '#/components/schemas/SchedulerConfig'
        },
        analysis: {
            '$ref': '#/components/schemas/ModelDefaults'
        },
        writing: {
            '$ref': '#/components/schemas/ModelDefaults'
        },
        search: {
            '$ref': '#/components/schemas/SearchConfig'
        },
        orchestrator: {
            '$ref': '#/components/schemas/OrchestratorConfig'
        }
    },
    type: 'object',
    required: ['llm_providers', 'scheduler', 'analysis', 'writing', 'search', 'orchestrator'],
    title: 'SystemConfigPublic'
} as const;

export const SystemConfigUpdateSchema = {
    properties: {
        kimi_api_key: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Kimi Api Key'
        },
        claude_api_key: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Claude Api Key'
        },
        openai_api_key: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Openai Api Key'
        },
        scheduler: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/SchedulerConfig'
                },
                {
                    type: 'null'
                }
            ]
        },
        analysis: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ModelDefaults'
                },
                {
                    type: 'null'
                }
            ]
        },
        writing: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ModelDefaults'
                },
                {
                    type: 'null'
                }
            ]
        },
        search: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/SearchConfig'
                },
                {
                    type: 'null'
                }
            ]
        },
        orchestrator: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/OrchestratorConfig'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    title: 'SystemConfigUpdate'
} as const;

export const TaskRunPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        task_type: {
            type: 'string',
            enum: ['analyze', 'fetch', 'workflow'],
            title: 'Task Type'
        },
        celery_task_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Celery Task Id'
        },
        triggered_by: {
            type: 'string',
            enum: ['manual', 'scheduler', 'agent'],
            title: 'Triggered By'
        },
        triggered_by_label: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Triggered By Label'
        },
        entity_type: {
            anyOf: [
                {
                    type: 'string',
                    enum: ['article', 'source']
                },
                {
                    type: 'null'
                }
            ],
            title: 'Entity Type'
        },
        entity_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Entity Id'
        },
        entity_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Entity Name'
        },
        status: {
            type: 'string',
            enum: ['pending', 'running', 'done', 'failed'],
            title: 'Status'
        },
        error_message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error Message'
        },
        workflow_run_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Workflow Run Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        started_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Started At'
        },
        ended_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ended At'
        }
    },
    type: 'object',
    required: ['id', 'task_type', 'celery_task_id', 'triggered_by', 'triggered_by_label', 'entity_type', 'entity_id', 'entity_name', 'status', 'error_message', 'workflow_run_id', 'created_at', 'started_at', 'ended_at'],
    title: 'TaskRunPublic'
} as const;

export const TaskRunsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/TaskRunPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'TaskRunsPublic'
} as const;

export const ToolPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        parameters_schema: {
            additionalProperties: true,
            type: 'object',
            title: 'Parameters Schema'
        },
        executor: {
            type: 'string',
            title: 'Executor'
        },
        function_name: {
            type: 'string',
            title: 'Function Name'
        },
        is_builtin: {
            type: 'boolean',
            title: 'Is Builtin'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        category: {
            type: 'string',
            title: 'Category'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'name', 'description', 'parameters_schema', 'executor', 'function_name', 'is_builtin', 'is_active', 'category', 'created_at'],
    title: 'ToolPublic'
} as const;

export const ToolUpdateSchema = {
    properties: {
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        },
        category: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category'
        },
        parameters_schema: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parameters Schema'
        }
    },
    type: 'object',
    title: 'ToolUpdate'
} as const;

export const ToolsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ToolPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ToolsPublic'
} as const;

export const TriggerAnalysisRequestSchema = {
    properties: {
        article_id: {
            type: 'string',
            format: 'uuid',
            title: 'Article Id'
        },
        triggered_by: {
            type: 'string',
            enum: ['manual', 'agent'],
            title: 'Triggered By',
            default: 'manual'
        },
        triggered_by_label: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Triggered By Label'
        }
    },
    type: 'object',
    required: ['article_id'],
    title: 'TriggerAnalysisRequest'
} as const;

export const TriggerAnalysisResponseSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        },
        article_id: {
            type: 'string',
            title: 'Article Id'
        }
    },
    type: 'object',
    required: ['message', 'article_id'],
    title: 'TriggerAnalysisResponse'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Superuser',
            default: false
        },
        is_verified: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Verified',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserReadSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'email'],
    title: 'UserRead'
} as const;

export const UserUpdateSchema = {
    properties: {
        password: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        },
        is_superuser: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Superuser'
        },
        is_verified: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Verified'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserRead'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const WorkflowApproveSchema = {
    properties: {
        selected_title: {
            type: 'string',
            title: 'Selected Title'
        }
    },
    type: 'object',
    required: ['selected_title'],
    title: 'WorkflowApprove'
} as const;

export const WorkflowInputSchema = {
    properties: {
        article_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            title: 'Article Ids'
        },
        topic: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Topic'
        },
        content: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content'
        }
    },
    type: 'object',
    title: 'WorkflowInput'
} as const;

export const WorkflowRejectSchema = {
    properties: {
        feedback: {
            type: 'string',
            title: 'Feedback'
        }
    },
    type: 'object',
    required: ['feedback'],
    title: 'WorkflowReject'
} as const;

export const WorkflowRunCreateSchema = {
    properties: {
        type: {
            type: 'string',
            title: 'Type',
            default: 'writing'
        },
        article_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            title: 'Article Ids'
        },
        topic: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Topic'
        }
    },
    type: 'object',
    title: 'WorkflowRunCreate'
} as const;

export const WorkflowRunPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        type: {
            type: 'string',
            title: 'Type'
        },
        input: {
            '$ref': '#/components/schemas/WorkflowInput'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        steps: {
            items: {
                '$ref': '#/components/schemas/AgentStep'
            },
            type: 'array',
            title: 'Steps'
        },
        parent_run_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Run Id'
        },
        user_feedback: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Feedback'
        },
        final_output: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Final Output'
        },
        created_by: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created By'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        use_orchestrator: {
            type: 'boolean',
            title: 'Use Orchestrator'
        },
        routing_log: {
            items: {
                '$ref': '#/components/schemas/RoutingEvent'
            },
            type: 'array',
            title: 'Routing Log'
        },
        iteration_count: {
            type: 'integer',
            title: 'Iteration Count'
        }
    },
    type: 'object',
    required: ['id', 'type', 'input', 'status', 'steps', 'parent_run_id', 'user_feedback', 'final_output', 'created_by', 'created_at', 'use_orchestrator', 'routing_log', 'iteration_count'],
    title: 'WorkflowRunPublic'
} as const;

export const WorkflowRunsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/WorkflowRunPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'WorkflowRunsPublic'
} as const;

export const loginSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_auth-auth:jwt.login'
} as const;