// This file is auto-generated by @hey-api/openapi-ts

export type AgentConfigCreate = {
    name: string;
    role: string;
    responsibilities?: string;
    system_prompt?: string;
    model_provider?: 'kimi' | 'openai';
    model_id?: string;
    workflow_order?: number;
    is_active?: boolean;
    skills?: Array<(string)>;
    tools?: Array<(string)>;
    max_iterations?: number;
};

export type model_provider = 'kimi' | 'openai';

export type AgentConfigPublic = {
    id: string;
    name: string;
    role: string;
    responsibilities: string;
    system_prompt: string;
    model_provider: string;
    model_id: string;
    workflow_order: number;
    is_active: boolean;
    skills: Array<(string)>;
    tools: Array<(string)>;
    max_iterations: number;
    created_at: string;
};

export type AgentConfigsPublic = {
    data: Array<AgentConfigPublic>;
    count: number;
};

export type AgentConfigUpdate = {
    name?: (string | null);
    role?: (string | null);
    responsibilities?: (string | null);
    system_prompt?: (string | null);
    model_provider?: ('kimi' | 'openai' | null);
    model_id?: (string | null);
    workflow_order?: (number | null);
    is_active?: (boolean | null);
    skills?: (Array<(string)> | null);
    tools?: (Array<(string)> | null);
    max_iterations?: (number | null);
};

export type AgentStep = {
    id?: string;
    agent_id?: (string | null);
    agent_name: string;
    role: string;
    input?: string;
    output?: string;
    thinking?: (string | null);
    title_candidates?: Array<(string)>;
    status?: string;
    started_at?: (string | null);
    ended_at?: (string | null);
    messages?: Array<{
        [key: string]: unknown;
    }>;
    tools_used?: Array<(string)>;
    skills_activated?: Array<(string)>;
    iteration_count?: number;
};

export type AnalysesPublic = {
    data: Array<ArticleAnalysisPublic>;
    count: number;
};

export type ApiConfig = {
    items_path: string;
    title_field: string;
    content_field: string;
    url_field: string;
    author_field?: (string | null);
    published_at_field?: (string | null);
};

export type ArticleAnalysisPublic = {
    id: string;
    article_id: string;
    quality_score: number;
    quality_breakdown: QualityBreakdown;
    hook_type: string;
    framework: string;
    emotional_triggers: Array<(string)>;
    key_phrases: Array<(string)>;
    keywords: Array<(string)>;
    structure: ArticleStructure;
    style: ArticleStyle;
    target_audience: string;
    created_at: string;
};

export type ArticleDetail = {
    id: string;
    source_id: (string | null);
    title: string;
    url: (string | null);
    author: (string | null);
    published_at: (string | null);
    status: string;
    input_type: string;
    created_at: string;
    quality_score?: (number | null);
    content: string;
    analysis?: ({
    [key: string]: unknown;
} | null);
};

export type ArticlePublic = {
    id: string;
    source_id: (string | null);
    title: string;
    url: (string | null);
    author: (string | null);
    published_at: (string | null);
    status: string;
    input_type: string;
    created_at: string;
    quality_score?: (number | null);
};

export type ArticlesPublic = {
    data: Array<ArticlePublic>;
    count: number;
};

export type ArticleStructure = {
    intro?: string;
    body_sections?: Array<(string)>;
    cta?: string;
};

export type ArticleStyle = {
    tone?: string;
    formality?: string;
    avg_sentence_length?: number;
};

export type BearerResponse = {
    access_token: string;
    token_type: string;
};

export type Body_auth_reset_forgot_password = {
    email: string;
};

export type Body_auth_reset_reset_password = {
    token: string;
    password: string;
};

export type Body_auth_verify_request_token = {
    email: string;
};

export type Body_auth_verify_verify = {
    token: string;
};

export type DraftPublic = {
    id: string;
    source_article_ids: Array<(string)>;
    workflow_run_id: (string | null);
    title: string;
    title_candidates: Array<(string)>;
    content: string;
    status: string;
    edit_history: Array<EditHistoryEntry>;
    created_at: string;
};

export type DraftsPublic = {
    data: Array<DraftPublic>;
    count: number;
};

export type DraftUpdate = {
    title?: (string | null);
    content?: (string | null);
    status?: (string | null);
};

export type EditHistoryEntry = {
    content: string;
    edited_at?: string;
    note?: string;
};

export type ErrorModel = {
    detail: (string | {
    [key: string]: (string);
});
};

export type FetchConfig = {
    interval_minutes?: number;
    max_items_per_fetch?: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type LLMProviderPublic = {
    api_key_masked?: (string | null);
    default_model: string;
};

export type LLMProvidersPublic = {
    kimi: LLMProviderPublic;
    claude: LLMProviderPublic;
    openai: LLMProviderPublic;
};

export type login = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Message = {
    message: string;
};

export type ModelDefaults = {
    default_model_provider?: string;
    default_model_id?: string;
};

export type OrchestratorConfig = {
    enabled?: boolean;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type QualityBreakdown = {
    content_depth?: number;
    readability?: number;
    originality?: number;
    virality_potential?: number;
};

export type RewriteSectionRequest = {
    selected_text: string;
    context?: string;
};

export type RewriteSectionResponse = {
    rewritten_text: string;
};

export type RoutingEvent = {
    timestamp?: string;
    from_agent: string;
    to_agent: string;
    reason?: string;
};

export type SchedulerConfig = {
    default_interval_minutes?: number;
    max_concurrent_fetches?: number;
};

export type SearchConfig = {
    tavily_api_key?: string;
};

export type SkillCreate = {
    name: string;
    description?: string;
    body?: string;
    scripts?: Array<SkillScript>;
    needs_network?: boolean;
    is_active?: boolean;
    source?: 'imported' | 'user';
    imported_from?: (string | null);
};

export type source = 'imported' | 'user';

export type SkillImportBody = {
    content?: (string | null);
    url?: (string | null);
};

export type SkillPublic = {
    id: string;
    name: string;
    description: string;
    body: string;
    scripts: Array<SkillScript>;
    needs_network: boolean;
    is_active: boolean;
    source: string;
    imported_from: (string | null);
    created_at: string;
    updated_at: string;
};

/**
 * A script bundled with a skill.
 */
export type SkillScript = {
    filename: string;
    content: string;
    language?: string;
};

export type SkillsPublic = {
    data: Array<SkillPublic>;
    count: number;
};

export type SkillUpdate = {
    description?: (string | null);
    body?: (string | null);
    scripts?: (Array<SkillScript> | null);
    needs_network?: (boolean | null);
    is_active?: (boolean | null);
};

export type SourceCreate = {
    name: string;
    type: string;
    url: string;
    api_key?: (string | null);
    headers?: ({
    [key: string]: unknown;
} | null);
    api_config?: (ApiConfig | null);
    fetch_config?: FetchConfig;
    is_active?: boolean;
};

export type SourcePublic = {
    id: string;
    name: string;
    type: string;
    url: string;
    api_config: (ApiConfig | null);
    fetch_config: FetchConfig;
    is_active: boolean;
    last_fetched_at: (string | null);
    created_at: string;
};

export type SourcesPublic = {
    data: Array<SourcePublic>;
    count: number;
};

export type SourceUpdate = {
    name?: (string | null);
    url?: (string | null);
    api_key?: (string | null);
    headers?: ({
    [key: string]: unknown;
} | null);
    api_config?: (ApiConfig | null);
    fetch_config?: (FetchConfig | null);
    is_active?: (boolean | null);
};

export type SubmitResponse = {
    article_id: string;
    status: string;
    message: string;
};

export type SubmitText = {
    mode?: string;
    title?: string;
    content?: string;
    url?: string;
};

export type SystemConfigPublic = {
    llm_providers: LLMProvidersPublic;
    scheduler: SchedulerConfig;
    analysis: ModelDefaults;
    writing: ModelDefaults;
    search: SearchConfig;
    orchestrator: OrchestratorConfig;
};

export type SystemConfigUpdate = {
    kimi_api_key?: (string | null);
    claude_api_key?: (string | null);
    openai_api_key?: (string | null);
    scheduler?: (SchedulerConfig | null);
    analysis?: (ModelDefaults | null);
    writing?: (ModelDefaults | null);
    search?: (SearchConfig | null);
    orchestrator?: (OrchestratorConfig | null);
};

export type ToolPublic = {
    id: string;
    name: string;
    description: string;
    parameters_schema: {
        [key: string]: unknown;
    };
    executor: string;
    function_name: string;
    is_builtin: boolean;
    is_active: boolean;
    category: string;
    created_at: string;
};

export type ToolsPublic = {
    data: Array<ToolPublic>;
    count: number;
};

export type ToolUpdate = {
    description?: (string | null);
    is_active?: (boolean | null);
    category?: (string | null);
    parameters_schema?: ({
    [key: string]: unknown;
} | null);
};

export type TriggerAnalysisRequest = {
    article_id: string;
};

export type TriggerAnalysisResponse = {
    message: string;
    article_id: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    password: string;
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
    is_verified?: (boolean | null);
    full_name?: (string | null);
};

export type UserRead = {
    id: string;
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    is_verified?: boolean;
    full_name?: (string | null);
    created_at?: (string | null);
};

export type UsersPublic = {
    data: Array<UserRead>;
    count: number;
};

export type UserUpdate = {
    password?: (string | null);
    email?: (string | null);
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
    is_verified?: (boolean | null);
    full_name?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type WorkflowApprove = {
    selected_title: string;
};

export type WorkflowInput = {
    article_ids?: Array<(string)>;
    topic?: (string | null);
    content?: (string | null);
};

export type WorkflowReject = {
    feedback: string;
};

export type WorkflowRunCreate = {
    type?: string;
    article_ids?: Array<(string)>;
    topic?: (string | null);
};

export type WorkflowRunPublic = {
    id: string;
    type: string;
    input: WorkflowInput;
    status: string;
    steps: Array<AgentStep>;
    parent_run_id: (string | null);
    user_feedback: (string | null);
    final_output: (string | null);
    created_by: (string | null);
    created_at: string;
    use_orchestrator: boolean;
    routing_log: Array<RoutingEvent>;
    iteration_count: number;
};

export type WorkflowRunsPublic = {
    data: Array<WorkflowRunPublic>;
    count: number;
};

export type AgentsListAgentsResponse = (AgentConfigsPublic);

export type AgentsCreateAgentData = {
    requestBody: AgentConfigCreate;
};

export type AgentsCreateAgentResponse = (AgentConfigPublic);

export type AgentsGetAgentData = {
    id: string;
};

export type AgentsGetAgentResponse = (AgentConfigPublic);

export type AgentsUpdateAgentData = {
    id: string;
    requestBody: AgentConfigUpdate;
};

export type AgentsUpdateAgentResponse = (AgentConfigPublic);

export type AgentsDeleteAgentData = {
    id: string;
};

export type AgentsDeleteAgentResponse = (void);

export type AgentsGetAvailableModelsResponse = (unknown);

export type AnalysesListAnalysesData = {
    limit?: number;
    skip?: number;
};

export type AnalysesListAnalysesResponse = (AnalysesPublic);

export type AnalysesTriggerAnalysisData = {
    requestBody: TriggerAnalysisRequest;
};

export type AnalysesTriggerAnalysisResponse = (TriggerAnalysisResponse);

export type AnalysesGetAnalysisData = {
    id: string;
};

export type AnalysesGetAnalysisResponse = (ArticleAnalysisPublic);

export type ArticlesListArticlesData = {
    inputType?: (string | null);
    limit?: number;
    skip?: number;
    sort?: string;
    sourceId?: (string | null);
    status?: (string | null);
};

export type ArticlesListArticlesResponse = (ArticlesPublic);

export type ArticlesGetArticleData = {
    id: string;
};

export type ArticlesGetArticleResponse = (ArticleDetail);

export type ArticlesArchiveArticleData = {
    id: string;
};

export type ArticlesArchiveArticleResponse = (ArticlePublic);

export type AuthAuthJwtLoginData = {
    formData: login;
};

export type AuthAuthJwtLoginResponse = (BearerResponse);

export type AuthAuthJwtLogoutResponse = (unknown);

export type AuthRegisterRegisterData = {
    requestBody: UserCreate;
};

export type AuthRegisterRegisterResponse = (UserRead);

export type AuthResetForgotPasswordData = {
    requestBody: Body_auth_reset_forgot_password;
};

export type AuthResetForgotPasswordResponse = (unknown);

export type AuthResetResetPasswordData = {
    requestBody: Body_auth_reset_reset_password;
};

export type AuthResetResetPasswordResponse = (unknown);

export type AuthVerifyRequestTokenData = {
    requestBody: Body_auth_verify_request_token;
};

export type AuthVerifyRequestTokenResponse = (unknown);

export type AuthVerifyVerifyData = {
    requestBody: Body_auth_verify_verify;
};

export type AuthVerifyVerifyResponse = (UserRead);

export type DraftsListDraftsData = {
    limit?: number;
    skip?: number;
    status?: (string | null);
};

export type DraftsListDraftsResponse = (DraftsPublic);

export type DraftsGetDraftData = {
    id: string;
};

export type DraftsGetDraftResponse = (DraftPublic);

export type DraftsUpdateDraftData = {
    id: string;
    requestBody: DraftUpdate;
};

export type DraftsUpdateDraftResponse = (DraftPublic);

export type DraftsDeleteDraftData = {
    id: string;
};

export type DraftsDeleteDraftResponse = (void);

export type DraftsApproveDraftData = {
    id: string;
};

export type DraftsApproveDraftResponse = (DraftPublic);

export type DraftsExportDraftData = {
    format?: string;
    id: string;
};

export type DraftsExportDraftResponse = (unknown);

export type DraftsRewriteSectionData = {
    id: string;
    requestBody: RewriteSectionRequest;
};

export type DraftsRewriteSectionResponse = (RewriteSectionResponse);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserRead);

export type SkillsListSkillsData = {
    limit?: number;
    skip?: number;
};

export type SkillsListSkillsResponse = (SkillsPublic);

export type SkillsCreateSkillData = {
    requestBody: SkillCreate;
};

export type SkillsCreateSkillResponse = (SkillPublic);

export type SkillsGetSkillData = {
    skillId: string;
};

export type SkillsGetSkillResponse = (SkillPublic);

export type SkillsUpdateSkillData = {
    requestBody: SkillUpdate;
    skillId: string;
};

export type SkillsUpdateSkillResponse = (SkillPublic);

export type SkillsDeleteSkillData = {
    skillId: string;
};

export type SkillsDeleteSkillResponse = (void);

export type SkillsImportSkillData = {
    requestBody: SkillImportBody;
};

export type SkillsImportSkillResponse = (SkillPublic);

export type SourcesListSourcesData = {
    limit?: number;
    skip?: number;
};

export type SourcesListSourcesResponse = (SourcesPublic);

export type SourcesCreateSourceData = {
    requestBody: SourceCreate;
};

export type SourcesCreateSourceResponse = (SourcePublic);

export type SourcesGetSourceData = {
    id: string;
};

export type SourcesGetSourceResponse = (SourcePublic);

export type SourcesUpdateSourceData = {
    id: string;
    requestBody: SourceUpdate;
};

export type SourcesUpdateSourceResponse = (SourcePublic);

export type SourcesDeleteSourceData = {
    id: string;
};

export type SourcesDeleteSourceResponse = (void);

export type SourcesTriggerFetchData = {
    id: string;
};

export type SourcesTriggerFetchResponse = (Message);

export type SubmitSubmitArticleData = {
    requestBody: SubmitText;
};

export type SubmitSubmitArticleResponse = (SubmitResponse);

export type SystemConfigGetSystemConfigResponse = (SystemConfigPublic);

export type SystemConfigUpdateSystemConfigData = {
    requestBody: SystemConfigUpdate;
};

export type SystemConfigUpdateSystemConfigResponse = (SystemConfigPublic);

export type ToolsListToolsResponse = (ToolsPublic);

export type ToolsUpdateToolData = {
    requestBody: ToolUpdate;
    toolId: string;
};

export type ToolsUpdateToolResponse = (ToolPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserRead);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersUsersCurrentUserResponse = (UserRead);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUsersPatchCurrentUserData = {
    requestBody: UserUpdate;
};

export type UsersUsersPatchCurrentUserResponse = (UserRead);

export type UsersUsersUserData = {
    id: string;
};

export type UsersUsersUserResponse = (UserRead);

export type UsersUsersPatchUserData = {
    id: string;
    requestBody: UserUpdate;
};

export type UsersUsersPatchUserResponse = (UserRead);

export type UsersUsersDeleteUserData = {
    id: string;
};

export type UsersUsersDeleteUserResponse = (void);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type WorkflowsListWorkflowsData = {
    limit?: number;
    skip?: number;
};

export type WorkflowsListWorkflowsResponse = (WorkflowRunsPublic);

export type WorkflowsTriggerWorkflowData = {
    requestBody: WorkflowRunCreate;
};

export type WorkflowsTriggerWorkflowResponse = (WorkflowRunPublic);

export type WorkflowsGetWorkflowData = {
    id: string;
};

export type WorkflowsGetWorkflowResponse = (WorkflowRunPublic);

export type WorkflowsWorkflowStreamData = {
    id: string;
};

export type WorkflowsWorkflowStreamResponse = (unknown);

export type WorkflowsApproveWorkflowData = {
    id: string;
    requestBody: WorkflowApprove;
};

export type WorkflowsApproveWorkflowResponse = (WorkflowRunPublic);

export type WorkflowsRejectWorkflowData = {
    id: string;
    requestBody: WorkflowReject;
};

export type WorkflowsRejectWorkflowResponse = (WorkflowRunPublic);

export type WorkflowsAbortWorkflowData = {
    id: string;
};

export type WorkflowsAbortWorkflowResponse = (Message);