// This file is auto-generated by @hey-api/openapi-ts

export type AgentConfigCreate = {
    name: string;
    role: string;
    responsibilities?: string;
    system_prompt?: string;
    model_config_name?: string;
    workflow_order?: number;
    is_active?: boolean;
    skills?: Array<(string)>;
    tools?: Array<(string)>;
    max_iterations?: number;
    analysis_config?: AnalysisConfig;
    react_config?: ReactConfig;
};

export type AgentConfigPublic = {
    id: string;
    name: string;
    role: string;
    responsibilities: string;
    system_prompt: string;
    model_config_name: string;
    workflow_order: number;
    is_active: boolean;
    skills: Array<(string)>;
    tools: Array<(string)>;
    max_iterations: number;
    analysis_config: AnalysisConfig;
    react_config: ReactConfig;
    created_at: string;
    updated_at: string;
};

export type AgentConfigsPublic = {
    data: Array<AgentConfigPublic>;
    count: number;
};

export type AgentConfigUpdate = {
    name?: (string | null);
    role?: (string | null);
    responsibilities?: (string | null);
    system_prompt?: (string | null);
    model_config_name?: (string | null);
    workflow_order?: (number | null);
    is_active?: (boolean | null);
    skills?: (Array<(string)> | null);
    tools?: (Array<(string)> | null);
    max_iterations?: (number | null);
    analysis_config?: (AnalysisConfig | null);
    react_config?: (ReactConfig | null);
};

export type AgentStep = {
    id?: string;
    agent_id?: (string | null);
    agent_name: string;
    role: string;
    input?: string;
    output?: string;
    thinking?: (string | null);
    title_candidates?: Array<(string)>;
    status?: string;
    started_at?: (string | null);
    ended_at?: (string | null);
    messages?: Array<{
        [key: string]: unknown;
    }>;
    tools_used?: Array<(string)>;
    skills_activated?: Array<(string)>;
    iteration_count?: number;
};

export type AnalysesPublic = {
    data: Array<ArticleAnalysisPublic>;
    count: number;
};

/**
 * 分析配置
 */
export type AnalysisConfig = {
    /**
     * 是否启用知识库对比
     */
    enable_kb_comparison?: boolean;
    /**
     * 是否启用外部搜索
     */
    enable_web_search?: boolean;
    /**
     * 对比文章数量
     */
    comparison_count?: number;
    /**
     * 分析深度
     */
    analysis_depth?: string;
};

export type AnalysisTraceResponse = {
    article_id: string;
    trace: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * 分析追溯步骤
 */
export type AnalysisTraceStep = {
    step_index: number;
    /**
     * 步骤名称
     */
    step_name?: string;
    /**
     * 步骤类型 (thought/tool_call/observation/conclusion/reflection)
     */
    step_type?: string;
    /**
     * 输入摘要
     */
    input_summary?: string;
    /**
     * 输出摘要
     */
    output_summary?: string;
    messages_sent?: Array<unknown>;
    raw_response?: string;
    parsed_ok?: boolean;
    duration_ms?: number;
    timestamp?: string;
    /**
     * 工具调用详情
     */
    tool_calls?: Array<ToolCallDetail>;
    /**
     * 并行组标识
     */
    parallel_group?: (string | null);
    /**
     * 并行组内索引
     */
    parallel_index?: (number | null);
};

export type ApiConfig = {
    items_path: string;
    title_field: string;
    content_field: string;
    url_field: string;
    author_field?: (string | null);
    published_at_field?: (string | null);
};

export type ArticleAnalysisPublic = {
    id: string;
    article_id: string;
    quality_score: number;
    quality_breakdown: QualityBreakdown;
    quality_score_details: Array<QualityScoreDetail>;
    comparison_references: Array<ComparisonReferenceEmbedded>;
    analysis_summary: string;
    improvement_suggestions: Array<(string)>;
    rubric_version: string;
    analysis_duration_ms: number;
    hook_type: string;
    framework: string;
    emotional_triggers: Array<(string)>;
    key_phrases: Array<(string)>;
    keywords: Array<(string)>;
    structure: ArticleStructure;
    style: ArticleStyle;
    target_audience: string;
    trace: Array<AnalysisTraceStep>;
    created_at: string;
};

export type ArticleDetail = {
    id: string;
    source_id: (string | null);
    title: string;
    url: (string | null);
    author: (string | null);
    published_at: (string | null);
    status: string;
    input_type: string;
    refine_status: string;
    created_at: string;
    quality_score?: (number | null);
    content: string;
    content_md?: (string | null);
    analysis?: ({
    [key: string]: unknown;
} | null);
};

export type ArticlePublic = {
    id: string;
    source_id: (string | null);
    title: string;
    url: (string | null);
    author: (string | null);
    published_at: (string | null);
    status: string;
    input_type: string;
    refine_status: string;
    created_at: string;
    quality_score?: (number | null);
};

export type ArticlesPublic = {
    data: Array<ArticlePublic>;
    count: number;
};

export type ArticleStructure = {
    intro?: string;
    body_sections?: Array<(string)>;
    cta?: string;
};

export type ArticleStyle = {
    tone?: string;
    formality?: string;
    avg_sentence_length?: number;
};

export type ArticleTitleUpdate = {
    title: string;
};

export type BearerResponse = {
    access_token: string;
    token_type: string;
};

export type Body_auth_reset_forgot_password = {
    email: string;
};

export type Body_auth_reset_reset_password = {
    token: string;
    password: string;
};

export type Body_auth_verify_request_token = {
    email: string;
};

export type Body_auth_verify_verify = {
    token: string;
};

/**
 * 嵌入的对比参考
 */
export type ComparisonReferenceEmbedded = {
    /**
     * 来源 (knowledge_base | external)
     */
    source: string;
    /**
     * 知识库文章ID
     */
    kb_article_id?: (string | null);
    /**
     * 知识库文章标题
     */
    kb_article_title?: (string | null);
    /**
     * 外部参考ID
     */
    external_ref_id?: (string | null);
    /**
     * 外部文章URL
     */
    external_url?: (string | null);
    /**
     * 外部文章标题
     */
    external_title?: (string | null);
    /**
     * 质量分数
     */
    quality_score?: (number | null);
    /**
     * 相似度分数
     */
    similarity_score?: number;
    /**
     * 关键差异
     */
    key_differences?: Array<(string)>;
    /**
     * 可借鉴之处
     */
    learnings?: Array<(string)>;
    /**
     * 对方优势
     */
    advantages?: Array<(string)>;
};

export type DraftPublic = {
    id: string;
    source_article_ids: Array<(string)>;
    workflow_run_id: (string | null);
    title: string;
    title_candidates: Array<(string)>;
    content: string;
    status: string;
    edit_history: Array<EditHistoryEntry>;
    created_at: string;
};

export type DraftsPublic = {
    data: Array<DraftPublic>;
    count: number;
};

export type DraftUpdate = {
    title?: (string | null);
    content?: (string | null);
    status?: (string | null);
};

export type EditHistoryEntry = {
    content: string;
    edited_at?: string;
    note?: string;
};

export type ErrorModel = {
    detail: (string | {
    [key: string]: (string);
});
};

export type ExternalReferenceCreate = {
    url: string;
    title: string;
    source?: string;
    content?: string;
    content_snippet?: string;
    search_query?: string;
    metadata?: {
        [key: string]: unknown;
    };
};

export type ExternalReferenceDetail = {
    id: string;
    url: string;
    title: string;
    source: string;
    content_snippet: string;
    fetched_at: string;
    search_query: string;
    metadata: {
        [key: string]: unknown;
    };
    referencer_article_ids: Array<(string)>;
    created_at: string;
    updated_at: string;
    content: string;
};

export type ExternalReferencePublic = {
    id: string;
    url: string;
    title: string;
    source: string;
    content_snippet: string;
    fetched_at: string;
    search_query: string;
    metadata: {
        [key: string]: unknown;
    };
    referencer_article_ids: Array<(string)>;
    created_at: string;
    updated_at: string;
};

export type ExternalReferencesPublic = {
    data: Array<ExternalReferencePublic>;
    count: number;
};

export type ExternalReferenceUpdate = {
    title?: (string | null);
    content?: (string | null);
    content_snippet?: (string | null);
    metadata?: ({
    [key: string]: unknown;
} | null);
};

export type FetchConfig = {
    interval_minutes?: number;
    max_items_per_fetch?: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type LLMModelConfigCreate = {
    name: string;
    provider_type?: 'openai_compatible' | 'kimi';
    base_url?: (string | null);
    api_key?: (string | null);
    model_id: string;
    is_active?: boolean;
};

export type provider_type = 'openai_compatible' | 'kimi';

export type LLMModelConfigPublic = {
    id: string;
    name: string;
    provider_type: string;
    base_url: (string | null);
    api_key_masked: (string | null);
    model_id: string;
    is_active: boolean;
    created_at: string;
};

export type LLMModelConfigsPublic = {
    data: Array<LLMModelConfigPublic>;
    count: number;
};

export type LLMModelConfigUpdate = {
    name?: (string | null);
    provider_type?: ('openai_compatible' | 'kimi' | null);
    base_url?: (string | null);
    api_key?: (string | null);
    model_id?: (string | null);
    is_active?: (boolean | null);
};

export type LLMProviderPublic = {
    api_key_masked?: (string | null);
    default_model: string;
};

export type LLMProvidersPublic = {
    kimi: LLMProviderPublic;
    claude: LLMProviderPublic;
    openai: LLMProviderPublic;
};

export type login = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Message = {
    message: string;
};

export type ModelDefaults = {
    default_model_provider?: string;
    default_model_id?: string;
};

export type OrchestratorConfig = {
    enabled?: boolean;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type QualityBreakdown = {
    content_depth?: number;
    readability?: number;
    originality?: number;
    virality_potential?: number;
};

export type QualityRubricCreate = {
    version: string;
    name: string;
    description?: string;
    dimensions: Array<RubricDimension>;
    is_active?: boolean;
};

export type QualityRubricPublic = {
    id: string;
    version: string;
    name: string;
    description: string;
    dimensions: Array<RubricDimension>;
    is_active: boolean;
    created_at: string;
    updated_at: string;
};

export type QualityRubricsPublic = {
    data: Array<QualityRubricPublic>;
    count: number;
};

export type QualityRubricUpdate = {
    version?: (string | null);
    name?: (string | null);
    description?: (string | null);
    dimensions?: (Array<RubricDimension> | null);
    is_active?: (boolean | null);
};

/**
 * 维度评分详情
 */
export type QualityScoreDetail = {
    /**
     * 维度名称
     */
    dimension: string;
    /**
     * 分数 0-100
     */
    score: number;
    /**
     * 权重
     */
    weight: number;
    /**
     * 加权分数
     */
    weighted_score: number;
    /**
     * 评分依据说明
     */
    reasoning?: string;
    /**
     * 符合的评分档位描述
     */
    standard_matched?: string;
    /**
     * 支撑证据列表
     */
    evidences?: Array<ScoreEvidence>;
    /**
     * 改进建议列表
     */
    improvement_suggestions?: Array<(string)>;
};

/**
 * React Agent 配置
 */
export type ReactConfig = {
    /**
     * 最大步骤数
     */
    max_steps?: number;
    /**
     * 是否启用反思步骤
     */
    reflection_enabled?: boolean;
    /**
     * 是否并行执行维度分析
     */
    parallel_analysis?: boolean;
};

export type RewriteSectionRequest = {
    selected_text: string;
    context?: string;
};

export type RewriteSectionResponse = {
    rewritten_text: string;
};

export type RoutingEvent = {
    timestamp?: string;
    from_agent: string;
    to_agent: string;
    reason?: string;
};

/**
 * 评分档位标准
 */
export type RubricCriterion = {
    min_score: number;
    max_score: number;
    /**
     * 档位描述
     */
    description: string;
};

/**
 * 评分维度定义
 */
export type RubricDimension = {
    /**
     * 维度名称 (content_depth, readability, originality, virality_potential)
     */
    name: string;
    /**
     * 维度描述
     */
    description: string;
    /**
     * 权重
     */
    weight: number;
    /**
     * 评分档位
     */
    criteria?: Array<RubricCriterion>;
};

export type SchedulerConfig = {
    default_interval_minutes?: number;
    max_concurrent_fetches?: number;
};

/**
 * 评分证据
 */
export type ScoreEvidence = {
    /**
     * 原文引用
     */
    quote: string;
    /**
     * 上下文说明
     */
    context?: string;
};

export type SearchConfig = {
    tavily_api_key?: string;
};

export type SkillCreate = {
    name: string;
    description?: string;
    body?: string;
    scripts?: Array<SkillScript>;
    needs_network?: boolean;
    is_active?: boolean;
    source?: 'imported' | 'user';
    imported_from?: (string | null);
};

export type source = 'imported' | 'user';

export type SkillImportBody = {
    content?: (string | null);
    url?: (string | null);
};

export type SkillPublic = {
    id: string;
    name: string;
    description: string;
    body: string;
    scripts: Array<SkillScript>;
    needs_network: boolean;
    is_active: boolean;
    source: string;
    imported_from: (string | null);
    created_at: string;
    updated_at: string;
};

/**
 * A script bundled with a skill.
 */
export type SkillScript = {
    filename: string;
    content: string;
    language?: string;
};

export type SkillsPublic = {
    data: Array<SkillPublic>;
    count: number;
};

export type SkillUpdate = {
    description?: (string | null);
    body?: (string | null);
    scripts?: (Array<SkillScript> | null);
    needs_network?: (boolean | null);
    is_active?: (boolean | null);
};

export type SourceCreate = {
    name: string;
    type: string;
    url: string;
    api_key?: (string | null);
    headers?: ({
    [key: string]: unknown;
} | null);
    api_config?: (ApiConfig | null);
    fetch_config?: FetchConfig;
    is_active?: boolean;
};

export type SourcePublic = {
    id: string;
    name: string;
    type: string;
    url: string;
    api_config: (ApiConfig | null);
    fetch_config: FetchConfig;
    is_active: boolean;
    last_fetched_at: (string | null);
    created_at: string;
};

export type SourcesPublic = {
    data: Array<SourcePublic>;
    count: number;
};

export type SourceUpdate = {
    name?: (string | null);
    url?: (string | null);
    api_key?: (string | null);
    headers?: ({
    [key: string]: unknown;
} | null);
    api_config?: (ApiConfig | null);
    fetch_config?: (FetchConfig | null);
    is_active?: (boolean | null);
};

export type SubmitResponse = {
    article_id: string;
    status: string;
    message: string;
};

export type SubmitText = {
    mode?: string;
    title?: string;
    content?: string;
    url?: string;
};

export type SystemConfigPublic = {
    llm_providers: LLMProvidersPublic;
    scheduler: SchedulerConfig;
    analysis: ModelDefaults;
    writing: ModelDefaults;
    search: SearchConfig;
    orchestrator: OrchestratorConfig;
};

export type SystemConfigUpdate = {
    kimi_api_key?: (string | null);
    claude_api_key?: (string | null);
    openai_api_key?: (string | null);
    scheduler?: (SchedulerConfig | null);
    analysis?: (ModelDefaults | null);
    writing?: (ModelDefaults | null);
    search?: (SearchConfig | null);
    orchestrator?: (OrchestratorConfig | null);
};

export type TaskRunPublic = {
    id: string;
    task_type: 'analyze' | 'fetch' | 'refine' | 'workflow';
    celery_task_id: (string | null);
    triggered_by: 'manual' | 'scheduler' | 'agent';
    triggered_by_label: (string | null);
    entity_type: ('article' | 'source' | null);
    entity_id: (string | null);
    entity_name: (string | null);
    status: 'pending' | 'running' | 'done' | 'failed';
    error_message: (string | null);
    workflow_run_id: (string | null);
    created_at: string;
    started_at: (string | null);
    ended_at: (string | null);
};

export type task_type = 'analyze' | 'fetch' | 'refine' | 'workflow';

export type triggered_by = 'manual' | 'scheduler' | 'agent';

export type status = 'pending' | 'running' | 'done' | 'failed';

export type TaskRunsPublic = {
    data: Array<TaskRunPublic>;
    count: number;
};

/**
 * 工具调用详情
 */
export type ToolCallDetail = {
    tool_name: string;
    input_params?: {
        [key: string]: unknown;
    };
    output_summary?: string;
    success?: boolean;
    error_message?: string;
};

export type ToolPublic = {
    id: string;
    name: string;
    description: string;
    parameters_schema: {
        [key: string]: unknown;
    };
    executor: string;
    function_name: string;
    is_builtin: boolean;
    is_active: boolean;
    category: string;
    created_at: string;
};

export type ToolsPublic = {
    data: Array<ToolPublic>;
    count: number;
};

export type ToolUpdate = {
    description?: (string | null);
    is_active?: (boolean | null);
    category?: (string | null);
    parameters_schema?: ({
    [key: string]: unknown;
} | null);
};

export type TriggerAnalysisRequest = {
    article_id: string;
    triggered_by?: 'manual' | 'agent';
    triggered_by_label?: (string | null);
};

export type triggered_by2 = 'manual' | 'agent';

export type TriggerAnalysisResponse = {
    message: string;
    article_id: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    password: string;
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
    is_verified?: (boolean | null);
    full_name?: (string | null);
};

export type UserRead = {
    id: string;
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    is_verified?: boolean;
    full_name?: (string | null);
    created_at?: (string | null);
};

export type UsersPublic = {
    data: Array<UserRead>;
    count: number;
};

export type UserUpdate = {
    password?: (string | null);
    email?: (string | null);
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
    is_verified?: (boolean | null);
    full_name?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type WorkflowApprove = {
    selected_title: string;
};

export type WorkflowInput = {
    article_ids?: Array<(string)>;
    topic?: (string | null);
    content?: (string | null);
};

export type WorkflowReject = {
    feedback: string;
};

export type WorkflowRunCreate = {
    type?: string;
    article_ids?: Array<(string)>;
    topic?: (string | null);
    use_orchestrator?: boolean;
};

export type WorkflowRunPublic = {
    id: string;
    type: string;
    input: WorkflowInput;
    status: string;
    error_message: (string | null);
    steps: Array<AgentStep>;
    parent_run_id: (string | null);
    user_feedback: (string | null);
    final_output: (string | null);
    created_by: (string | null);
    created_at: string;
    use_orchestrator: boolean;
    routing_log: Array<RoutingEvent>;
    iteration_count: number;
};

export type WorkflowRunsPublic = {
    data: Array<WorkflowRunPublic>;
    count: number;
};

export type AgentsListAgentsResponse = (AgentConfigsPublic);

export type AgentsCreateAgentData = {
    requestBody: AgentConfigCreate;
};

export type AgentsCreateAgentResponse = (AgentConfigPublic);

export type AgentsGetAgentData = {
    id: string;
};

export type AgentsGetAgentResponse = (AgentConfigPublic);

export type AgentsUpdateAgentData = {
    id: string;
    requestBody: AgentConfigUpdate;
};

export type AgentsUpdateAgentResponse = (AgentConfigPublic);

export type AgentsDeleteAgentData = {
    id: string;
};

export type AgentsDeleteAgentResponse = (void);

export type AgentsGetAvailableModelsResponse = (unknown);

export type AnalysesListAnalysesData = {
    limit?: number;
    skip?: number;
};

export type AnalysesListAnalysesResponse = (AnalysesPublic);

export type AnalysesTriggerAnalysisData = {
    requestBody: TriggerAnalysisRequest;
};

export type AnalysesTriggerAnalysisResponse = (TriggerAnalysisResponse);

export type AnalysesGetAnalysisData = {
    articleId: string;
};

export type AnalysesGetAnalysisResponse = (ArticleAnalysisPublic);

export type AnalysesGetAnalysisTraceData = {
    articleId: string;
};

export type AnalysesGetAnalysisTraceResponse = (AnalysisTraceResponse);

export type ArticlesListArticlesData = {
    inputType?: (string | null);
    limit?: number;
    skip?: number;
    sort?: string;
    sourceId?: (string | null);
    status?: (string | null);
};

export type ArticlesListArticlesResponse = (ArticlesPublic);

export type ArticlesGetArticleData = {
    id: string;
};

export type ArticlesGetArticleResponse = (ArticleDetail);

export type ArticlesArchiveArticleData = {
    id: string;
};

export type ArticlesArchiveArticleResponse = (ArticlePublic);

export type ArticlesRefetchArticleData = {
    id: string;
};

export type ArticlesRefetchArticleResponse = (unknown);

export type ArticlesUpdateArticleTitleData = {
    id: string;
    requestBody: ArticleTitleUpdate;
};

export type ArticlesUpdateArticleTitleResponse = (ArticlePublic);

export type AuthAuthJwtLoginData = {
    formData: login;
};

export type AuthAuthJwtLoginResponse = (BearerResponse);

export type AuthAuthJwtLogoutResponse = (unknown);

export type AuthRegisterRegisterData = {
    requestBody: UserCreate;
};

export type AuthRegisterRegisterResponse = (UserRead);

export type AuthResetForgotPasswordData = {
    requestBody: Body_auth_reset_forgot_password;
};

export type AuthResetForgotPasswordResponse = (unknown);

export type AuthResetResetPasswordData = {
    requestBody: Body_auth_reset_reset_password;
};

export type AuthResetResetPasswordResponse = (unknown);

export type AuthVerifyRequestTokenData = {
    requestBody: Body_auth_verify_request_token;
};

export type AuthVerifyRequestTokenResponse = (unknown);

export type AuthVerifyVerifyData = {
    requestBody: Body_auth_verify_verify;
};

export type AuthVerifyVerifyResponse = (UserRead);

export type DraftsListDraftsData = {
    limit?: number;
    skip?: number;
    status?: (string | null);
};

export type DraftsListDraftsResponse = (DraftsPublic);

export type DraftsGetDraftData = {
    id: string;
};

export type DraftsGetDraftResponse = (DraftPublic);

export type DraftsUpdateDraftData = {
    id: string;
    requestBody: DraftUpdate;
};

export type DraftsUpdateDraftResponse = (DraftPublic);

export type DraftsDeleteDraftData = {
    id: string;
};

export type DraftsDeleteDraftResponse = (void);

export type DraftsApproveDraftData = {
    id: string;
};

export type DraftsApproveDraftResponse = (DraftPublic);

export type DraftsExportDraftData = {
    format?: string;
    id: string;
};

export type DraftsExportDraftResponse = (unknown);

export type DraftsRewriteSectionData = {
    id: string;
    requestBody: RewriteSectionRequest;
};

export type DraftsRewriteSectionResponse = (RewriteSectionResponse);

export type ExternalReferencesListExternalReferencesData = {
    limit?: number;
    search?: string;
    skip?: number;
    source?: string;
};

export type ExternalReferencesListExternalReferencesResponse = (ExternalReferencesPublic);

export type ExternalReferencesCreateExternalReferenceData = {
    requestBody: ExternalReferenceCreate;
};

export type ExternalReferencesCreateExternalReferenceResponse = (ExternalReferencePublic);

export type ExternalReferencesGetExternalReferenceData = {
    refId: string;
};

export type ExternalReferencesGetExternalReferenceResponse = (ExternalReferenceDetail);

export type ExternalReferencesUpdateExternalReferenceData = {
    refId: string;
    requestBody: ExternalReferenceUpdate;
};

export type ExternalReferencesUpdateExternalReferenceResponse = (ExternalReferencePublic);

export type ExternalReferencesDeleteExternalReferenceData = {
    refId: string;
};

export type ExternalReferencesDeleteExternalReferenceResponse = (Message);

export type ExternalReferencesRefetchExternalReferenceData = {
    refId: string;
};

export type ExternalReferencesRefetchExternalReferenceResponse = (ExternalReferencePublic);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LlmModelConfigsListLlmModelConfigsResponse = (LLMModelConfigsPublic);

export type LlmModelConfigsCreateLlmModelConfigData = {
    requestBody: LLMModelConfigCreate;
};

export type LlmModelConfigsCreateLlmModelConfigResponse = (LLMModelConfigPublic);

export type LlmModelConfigsUpdateLlmModelConfigData = {
    id: string;
    requestBody: LLMModelConfigUpdate;
};

export type LlmModelConfigsUpdateLlmModelConfigResponse = (LLMModelConfigPublic);

export type LlmModelConfigsDeleteLlmModelConfigData = {
    id: string;
};

export type LlmModelConfigsDeleteLlmModelConfigResponse = (void);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserRead);

export type RubricsListRubricsData = {
    limit?: number;
    skip?: number;
};

export type RubricsListRubricsResponse = (QualityRubricsPublic);

export type RubricsCreateRubricData = {
    requestBody: QualityRubricCreate;
};

export type RubricsCreateRubricResponse = (QualityRubricPublic);

export type RubricsGetActiveRubricResponse = (QualityRubricPublic);

export type RubricsGetRubricData = {
    rubricId: string;
};

export type RubricsGetRubricResponse = (QualityRubricPublic);

export type RubricsUpdateRubricData = {
    requestBody: QualityRubricUpdate;
    rubricId: string;
};

export type RubricsUpdateRubricResponse = (QualityRubricPublic);

export type RubricsDeleteRubricData = {
    rubricId: string;
};

export type RubricsDeleteRubricResponse = (Message);

export type RubricsActivateRubricData = {
    rubricId: string;
};

export type RubricsActivateRubricResponse = (QualityRubricPublic);

export type SkillsListSkillsData = {
    limit?: number;
    skip?: number;
};

export type SkillsListSkillsResponse = (SkillsPublic);

export type SkillsCreateSkillData = {
    requestBody: SkillCreate;
};

export type SkillsCreateSkillResponse = (SkillPublic);

export type SkillsGetSkillData = {
    skillId: string;
};

export type SkillsGetSkillResponse = (SkillPublic);

export type SkillsUpdateSkillData = {
    requestBody: SkillUpdate;
    skillId: string;
};

export type SkillsUpdateSkillResponse = (SkillPublic);

export type SkillsDeleteSkillData = {
    skillId: string;
};

export type SkillsDeleteSkillResponse = (void);

export type SkillsImportSkillData = {
    requestBody: SkillImportBody;
};

export type SkillsImportSkillResponse = (SkillPublic);

export type SourcesListSourcesData = {
    limit?: number;
    skip?: number;
};

export type SourcesListSourcesResponse = (SourcesPublic);

export type SourcesCreateSourceData = {
    requestBody: SourceCreate;
};

export type SourcesCreateSourceResponse = (SourcePublic);

export type SourcesGetSourceData = {
    id: string;
};

export type SourcesGetSourceResponse = (SourcePublic);

export type SourcesUpdateSourceData = {
    id: string;
    requestBody: SourceUpdate;
};

export type SourcesUpdateSourceResponse = (SourcePublic);

export type SourcesDeleteSourceData = {
    id: string;
};

export type SourcesDeleteSourceResponse = (void);

export type SourcesTriggerFetchData = {
    id: string;
};

export type SourcesTriggerFetchResponse = (Message);

export type SubmitSubmitArticleData = {
    requestBody: SubmitText;
};

export type SubmitSubmitArticleResponse = (SubmitResponse);

export type SystemConfigGetSystemConfigResponse = (SystemConfigPublic);

export type SystemConfigUpdateSystemConfigData = {
    requestBody: SystemConfigUpdate;
};

export type SystemConfigUpdateSystemConfigResponse = (SystemConfigPublic);

export type TaskRunsListTaskRunsData = {
    dateFrom?: (string | null);
    dateTo?: (string | null);
    entityId?: (string | null);
    limit?: number;
    skip?: number;
    status?: ('pending' | 'running' | 'done' | 'failed' | null);
    taskType?: ('analyze' | 'fetch' | 'refine' | 'workflow' | null);
    triggeredBy?: ('manual' | 'scheduler' | 'agent' | null);
};

export type TaskRunsListTaskRunsResponse = (TaskRunsPublic);

export type TaskRunsGetTaskRunData = {
    id: string;
};

export type TaskRunsGetTaskRunResponse = (TaskRunPublic);

export type ToolsListToolsResponse = (ToolsPublic);

export type ToolsUpdateToolData = {
    requestBody: ToolUpdate;
    toolId: string;
};

export type ToolsUpdateToolResponse = (ToolPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserRead);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersUsersCurrentUserResponse = (UserRead);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUsersPatchCurrentUserData = {
    requestBody: UserUpdate;
};

export type UsersUsersPatchCurrentUserResponse = (UserRead);

export type UsersUsersUserData = {
    id: string;
};

export type UsersUsersUserResponse = (UserRead);

export type UsersUsersPatchUserData = {
    id: string;
    requestBody: UserUpdate;
};

export type UsersUsersPatchUserResponse = (UserRead);

export type UsersUsersDeleteUserData = {
    id: string;
};

export type UsersUsersDeleteUserResponse = (void);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type WorkflowsListWorkflowsData = {
    limit?: number;
    skip?: number;
};

export type WorkflowsListWorkflowsResponse = (WorkflowRunsPublic);

export type WorkflowsTriggerWorkflowData = {
    requestBody: WorkflowRunCreate;
};

export type WorkflowsTriggerWorkflowResponse = (WorkflowRunPublic);

export type WorkflowsGetWorkflowData = {
    id: string;
};

export type WorkflowsGetWorkflowResponse = (WorkflowRunPublic);

export type WorkflowsWorkflowStreamData = {
    id: string;
};

export type WorkflowsWorkflowStreamResponse = (unknown);

export type WorkflowsApproveWorkflowData = {
    id: string;
    requestBody: WorkflowApprove;
};

export type WorkflowsApproveWorkflowResponse = (WorkflowRunPublic);

export type WorkflowsRejectWorkflowData = {
    id: string;
    requestBody: WorkflowReject;
};

export type WorkflowsRejectWorkflowResponse = (WorkflowRunPublic);

export type WorkflowsAbortWorkflowData = {
    id: string;
};

export type WorkflowsAbortWorkflowResponse = (Message);

export type WorkflowsRetryWorkflowData = {
    id: string;
};

export type WorkflowsRetryWorkflowResponse = (WorkflowRunPublic);